version: '2'
services:
  # live:
  #   build: ./docker/live
  #   environment:
  #     steemnode: "peer.proto.vit.tube"
  #   links:
  #     - mongo
  history:
    build: ./docker/history
    environment:
      steemnode: "peer.proto.vit.tube"
    links:
      - mongo
  sync:
    build: ./docker/sync
    environment:
      steemnode: "peer.proto.vit.tube"
    links:
      - mongo
  witnesses:
    build: ./docker/witnesses
    environment:
      steemnode: "peer.proto.vit.tube"
    links:
      - mongo
  development:
    build: ./docker/development
    links:
      - mongo
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
  mongodata:
    image: mongo:3.3.10
    volumes:
      - /data/db
    command: --break-mongo
  mongo:
    image: mongo:3.3.10
    volumes_from:
      - mongodata
    command: --smallfiles --rest
